# Generated by Django 6.0.4 on 2026-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_official', models.BooleanField(default=False)),
                ('field_map', models.JSONField(blank=True, default=dict)),
                ('inactive_fields', models.JSONField(default=list)),
                ('field_overrides', models.JSONField(blank=True, default=dict)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
