# Generated by Django 6.0.4 on 2026-05-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_official', models.BooleanField(default=False)),
                ('schemas', models.JSONField(blank=True, default=dict)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
