# Generated by Django 6.0.4 on 2026-05-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='field_overrides',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='schemas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='inactive_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
