# Generated by Django 6.0.4 on 2026-05-25 03:15

from django.db import migrations


def create_official_profiles(apps, schema_editor):
    ProfileModel = apps.get_model('sheets', 'ProfileModel')

    ProfileModel.objects.get_or_create(
        system_id='paranormal_order',
        display_name='Paranormal Order',
        is_official=True,
        schemas={
            "identity_schema": {
                "default": False,
                "added_fields": {},
                "field_overrides": {},
                "custom_schema": {
                    "name": "",
                    "level": 0,
                    "nex": 0,
                    "origin": "",
                    "class": ""
                }
            },
            "attributes_schema": {
                "default": False,
                "added_fields": {},
                "field_overrides": {},
                "custom_schema": {
                    "dex": 0,
                    "con": 0,
                    "int": 0,
                    "str": 0,
                    "pre": 0
                }
            },
            "status_schema": {
                "default": True,
                "added_fields": {
                    "effort": {
                        "current": 0,
                        "max": 0,
                        "temporary": 0
                    },
                    "determination": {
                        "current": 0,
                        "max": 0,
                        "temporary": 0
                    }
                },
                "field_overrides": {
                    "health": {
                        "current": 0,
                        "max": 0,
                        "temporary": 0
                    },
                    "sanity": {
                        "current": 0,
                        "max": 0,
                        "temporary": 0
                    },
                    "mana": None
                },
                "custom_schema": {}
            },
            "defense_schema": {
                "default": True,
                "added_fields": {},
                "field_overrides": {},
                "custom_schema": {}
            },
            "skills_item_schema": {
                "default": True,
                "added_fields": {
                    "temporary": 0
                },
                "field_overrides": {},
                "custom_schema": {}
            },
            "abilities_item_schema": {
                "default": True,
                "added_fields": {
                    "class": ""
                },
                "field_overrides": {},
                "custom_schema": {}
            },
            "spells_item_schema": {
                "default": True,
                "added_fields": {},
                "field_overrides": {},
                "custom_schema": {}
            },
            "inventory_item_schema": {
                "default": True,
                "added_fields": {
                    "item_type": 0,
                    "weapon_values": {},
                    "_weapon_values_example": {
                        "damage": "",
                        "damage_type": "",
                        "critical_range": 0,
                        "critical_mult": 0,
                        "handling": "",
                        "proficiency": ""
                    },
                    "category": 0,
                    "mods": [],
                    "tag": 0
                },
                "field_overrides": {},
                "custom_schema": {}
            },
            "custom_fields": {}
        }
    )


class Migration(migrations.Migration):
    dependencies = [
        ('sheets', '0001_initial'),
    ]
    operations = [migrations.RunPython(create_official_profiles),]
