# Generated by Django 6.0.4 on 2026-05-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_remove_profilemodel_field_overrides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='field_map',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='inactive_fields',
        ),
    ]
